### ISSUE TITLE
v3.7 纳管ZStack云账号且其同步完成后，该平台的二层网络状态不应该一直是init

### ISSUE THREAD

**Issue by zexi** [yunionio/yunioncloud#10737]
**What happened**:

![image](https://user-images.githubusercontent.com/10767027/114811592-f3981e80-9de0-11eb-9eec-b5f0856f5476.png)

**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Version (e.g. `kubectl get oc -n onecloud  -o yaml | grep -C 3 version`):

内部测试环境：

10.127.90.254
web账号/密码    demo/1
服务器账号/密码  root/1

**Comment by zexi** [comment]
@hoganlxj 麻烦跟踪下这个 bug

**Comment by hoganlxj** [comment]
好的
