### ISSUE TITLE
arm虚拟机保存系统镜像后，再次新建虚拟机应该能查询出该镜像

### ISSUE THREAD

**Issue by zexi** [yunionio/yunioncloud#10733]
[步骤]

1.arm虚拟机保存系统镜像，该镜像的os

arm虚拟机保存的系统镜像 os_arch=aarch64，
系统镜像 通过上传的arm镜像 os_arch=arm
2.再次新建arm虚拟机

[结果]

在新建arm虚拟机时，前端请求镜像（公共镜像和自定义镜像）的参数为os_arch=arm，导致保存的系统镜像查不到

![image](https://user-images.githubusercontent.com/10767027/114716634-d161ba80-9d66-11eb-83d0-78d2c49bad6c.png)

**Comment by zexi** [comment]
@hoganlxj

**Comment by hoganlxj** [comment]
收到
