### ISSUE TITLE
v3.7 windows系统（采用密码登录）的openstack虚拟机重置密码失败

### ISSUE THREAD

**Issue by zexi** [yunionio/yunioncloud#10739]
**What happened**:

![image](https://user-images.githubusercontent.com/10767027/114812685-0f9cbf80-9de3-11eb-867e-f2b6a0600cc2.png)
![image](https://user-images.githubusercontent.com/10767027/114812770-42df4e80-9de3-11eb-9db9-529734c1eebd.png)

**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Version (e.g. `kubectl get oc -n onecloud  -o yaml | grep -C 3 version`):

**Comment by ioito** [comment]
这个是openstack返回的错误
具体请看下面文件的最后几行，请检查openstack环境配置
https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/admin_password.py
