### ISSUE TITLE
 v3.6 前端新建私有云账号时前端不应该报错

### ISSUE THREAD

**Issue by zexi** [yunionio/yunioncloud#10740]
**What happened**:

![image](https://user-images.githubusercontent.com/10767027/114813014-c731d180-9de3-11eb-9a7a-50b6b654d2b0.png)

**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Version (e.g. `kubectl get oc -n onecloud  -o yaml | grep -C 3 version`):

**Comment by Easy-MJ** [comment]
![image](https://user-images.githubusercontent.com/11886313/115386966-a2d35c00-a20c-11eb-9571-69ec6a72909f.png)
