### ISSUE TITLE
Vote on new project name: openMHCP, UMHCP, Chachapoya, ChaCloud, ocafusion, etc.

### ISSUE THREAD

**Issue by swordqiu** [yunionio/yunioncloud#10788]
We are going to donate project to Apache Incubator. Due to potential trademark conflict, we are going to rename the project. The new name should meet the following criteria: 1. Not used by any coporation. 2. Not registered in US, EU, CN and india trademark registration. 3. No project with similar name on Github or Bitbuckets. 4. Not directly related to the donation company (yunion or one cloud).  Here are a list of candidate names and the exaplanations:

* openMHCP - open source multi/hybride cloud platform
* UMHCP - unified multi/hybrid cloud platform
* ChaCloud - Chakra Cloud, chakra, or 查克拉 in Chinese, which means power, energy, magic in different scenarios
* ocafusion - One Cloud is a fusion of many clouds
* other - please leave your suggestion in response, we will put it in the list if the above criteria are met

Many thanks.

Vote states(202014021):
ocafusion: 6 (zexi, hoganlxj, wanfuuyu, xybstone, tangchi-coder, willemJiang)
ChaCloud: 17 (dengju2020, zhasm, dong0320, osxlinux, we14578, bistuzx, Mxinhu, dbwiddis, lengband, zhaoxiangchun, tb365, hejiwen-com, swordqiu, rainzm, lj7xun, tristaZero, wcl6106)

**Comment by swordqiu** [comment]
Chachapoya+1

**Comment by ioito** [comment]
Chachapoya

**Comment by zexi** [comment]
ocafusion +1

**Comment by dengju2020** [comment]
ChaCloud

**Comment by zhasm** [comment]
My vote: ChaCloud.
* It has a similar pronunciation as チャクラ，chakra, or 查克拉 in Chinese.
* it is easier to pronounce and remember, comparing with other candidates.

**Comment by jackgao2015** [comment]
Chachapoya+1

**Comment by hoganlxj** [comment]
ocafusion

**Comment by dong0320** [comment]
ChaCloud

**Comment by wanfuuyu** [comment]
ocafusion

**Comment by pingp76** [comment]
Chachapoya

**Comment by zexi** [comment]
> My vote: ChaCloud.
> 
> * It has a similar pronunciation as チャクラ，chakra, or 查克拉 in Chinese, which means power, energy, magic in different scenarios.

This explanation of chakra is really interesting 🥷🏻.

**Comment by cnhotfire** [comment]
Chachapoya

**Comment by osxlinux** [comment]
ChaCloud +1

**Comment by we14578** [comment]
ChaCloud +1

**Comment by rainzm** [comment]
ChaCloud

**Comment by xybstone** [comment]
ocafusion

**Comment by tangchi-coder** [comment]
ocafusion

**Comment by houpeining** [comment]
Chachapoya + 1

**Comment by stringtang** [comment]
Chachapoya

**Comment by bistuzx** [comment]
ChaCloud

**Comment by Mxinhu** [comment]
Chachapoya

**Comment by dbwiddis** [comment]
Not active in this community but following the Apache incubator thread.  Either ChaCloud (1st choce) or Chachapoya (2nd choice)

**Comment by lengband** [comment]
ChaCloud

**Comment by zhaoxiangchun** [comment]
ChaCloud

**Comment by tb365** [comment]
ChaCloud

**Comment by wenlong113** [comment]
Chachapoya

**Comment by WillemJiang** [comment]
ocafusion +1

**Comment by dave2wave** [comment]
-1 on anything to do with Chachapoya.

**Comment by yousong** [comment]
> -1 on anything to do with Chachapoya.

@dave2wave , Hi Dave, thanks for coming by and welcome.  Can you share more details on the concerns?

**Comment by wanyaoqi** [comment]
Chachapoya

**Comment by hejiwen-com** [comment]
ChaCloud

**Comment by justinmclean** [comment]
Not that my vote counts but if it did I would be -1 on Chachapoya as it very hard to pronounce, remember or write down for most people. There may also be cultural reasons for not using it. I don't know how the group of people who associate with than name would feel about its use in this context. The Apache name was chosen 20 years ago, today it's unlikely that the foundation would come up with the same name. If you do go with ChaCloud I suggest you associate the name with chakra.

**Comment by justinmclean** [comment]
I would also do a trademark search and search for any project bytes same name. If they exist you may have to change the name later and that's a lot of work and can be disruptive to your community.

**Comment by dbwiddis** [comment]
> it very hard to pronounce, remember or write down

I'll also point out that if it becomes an Apache project you'd have the syllables "che" "cha" "cha" in rapid succession.

**Comment by swordqiu** [comment]
> Not that my vote counts but if it did I would be -1 on Chachapoya as it very hard to pronounce, remember or write down for most people. There may also be cultural reasons for not using it. I don't know how the group of people who associate with than name would feel about its use in this context. The Apache name was chosen 20 years ago, today it's unlikely that the foundation would come up with the same name. If you do go with ChaCloud I suggest you associate the name with chakra.

As you and some other people sugguest, Chachapoya might not be an appropriate project name, we would remove it from the candidate list. The meaning of ChaCloud would be interpreted as Chakra + Cloud.

**Comment by swordqiu** [comment]
For those who voted for Chachapoya, please revote.

ChaCloud+1

**Comment by swordqiu** [comment]
> I would also do a trademark search and search for any project bytes same name. If they exist you may have to change the name later and that's a lot of work and can be disruptive to your community.

@justinmclean It seems most people prefer ChaCloud. Could you please help verify ChaCloud is legitimate for a Apache Incubator project? Many thanks. I have search it against the trademark registries of US, EU, CN and india and found no records.

**Comment by rainzm** [comment]
ChaCloud

**Comment by lj7xun** [comment]
ChaCloud

**Comment by tristaZero** [comment]
Give my +1 to `ChaCloud`

**Comment by wcl6106** [comment]
ChaCloud

**Comment by tuohai666** [comment]
I'm also following the Apache incubator thread, I think the meaning of ChaCloud is fantasy. Just suggest that according to dbwiddis said, I'd remind Apache ChaCloud pronounces like /əˈpæt**ʃi tʃɑ**ː  klaʊd/. 

> > it very hard to pronounce, remember or write down
> 
> I'll also point out that if it becomes an Apache project you'd have the syllables "che" "cha" "cha" in rapid succession.

**Comment by WillemJiang** [comment]
+1 for ChaCloud.

**Comment by swordqiu** [comment]
ChaCloud will be chosen as new project name. Thanks for your votes.
