### ISSUE TITLE
3.7版本 系统管理员新建联系人后邮箱显示已验证，但是系统管理员修改该联系人的邮箱后，该邮箱却显示未验证。

### ISSUE THREAD

**Issue by wenlong113** [yunionio/yunioncloud#10803]
**What happened**:
10.127.90.244 
**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Version (e.g. `kubectl get oc -n onecloud  -o yaml | grep -C 3 version`):

**Comment by zexi** [comment]
This is not a CE(Community Edition) bug, so close it.
