### ISSUE TITLE
3.7版本 移动云对接没有同步下来安全组

### ISSUE THREAD

**Issue by wenlong113** [yunionio/yunioncloud#10800]
**What happened**:

**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Version (e.g. `kubectl get oc -n onecloud  -o yaml | grep -C 3 version`):
10.127.90.244

**Comment by wenlong113** [comment]
该安全组已关联虚拟机

**Comment by rainzm** [comment]
移动云暂时没有安全组相关的api，所以暂不支持。

**Comment by wenlong113** [comment]
谢谢，已知
