### ISSUE TITLE
kvm虚拟机迁移时不应该报镜像找不到的错误

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/yunioncloud#10814]
**What happened**:
kvm虚拟机迁移时因找不到镜像报错
**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Version (e.g. `kubectl get oc -n onecloud  -o yaml | grep -C 3 version`):

**Comment by zexi** [comment]
/close
PR: https://github.com/yunionio/yunioncloud/pull/10833 merged.
