### ISSUE TITLE
在系统默认导入的集群下新建容器实例不应该报错

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/yunioncloud#10918]
**What happened**:
![image](https://user-images.githubusercontent.com/32036395/115985833-40010c80-a5e0-11eb-8479-ef31a58eb610.png)

**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Version (e.g. `kubectl get oc -n onecloud  -o yaml | grep -C 3 version`):

**Comment by zexi** [comment]
这个问题我再看下，记得以前修复过，是最新的 v3.7 版本？
