### ISSUE TITLE
删除vmware云账号不应该报错

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/yunioncloud#10963]
**What happened**:
{
    "__reason__": {
        "reason": "purge host: purgeDisks for storage VMFS-10.127.40.4-datastore4: purge disk 2264b400-8da5-4a5d-8704-dd9097906204: {\"error\":{\"class\":\"NotEmptyError\",\"code\":406,\"data\":{\"fields\":[\"89968fff-112c-4433-8ac0-f42df3093691.vmdk\",\"2264b400-8da5-4a5d-8704-dd9097906204\"],\"id\":\"Virtual disk %s(%s) used by virtual servers\"},\"details\":\"Virtual disk 89968fff-112c-4433-8ac0-f42df3093691.vmdk(2264b400-8da5-4a5d-8704-dd9097906204) used by virtual servers\"}}",
        "stage": "on_init"
    },
    "__stage__": "OnAllCloudProviderDeleteComplete",
    "__status__": "error",
    "__task_name__": "CloudProviderDeleteTask"
}
**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Version (e.g. `kubectl get oc -n onecloud  -o yaml | grep -C 3 version`):

**Comment by rainzm** [comment]
我去看了下 这个应该是脏数据导致的，2号宿主机上面的一台虚拟机的磁盘跑到了4号宿主机的本地存储上。
