### ISSUE TITLE
天翼云 云账号 未能成功同步账号余额

### ISSUE THREAD

**Issue by jackgao2015** [yunionio/yunioncloud#11117]
**What happened**:
测试天翼云资源支持情况
**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Version (e.g. `kubectl get oc -n onecloud  -o yaml | grep -C 3 version`):
dcm.yungoal.com环境
![image](https://user-images.githubusercontent.com/11387540/118247380-b2755600-b4d5-11eb-81d3-56b1350e87af.png)

**Comment by tb365** [comment]
天翼云官方未开放余额查询接口
