### ISSUE TITLE
安全组删不掉

### ISSUE THREAD

**Issue by yangyanqi0805** [yunionio/yunioncloud#11133]
**What happened**:
https://10.127.100.231   demo  1   安全组点击删除，但是删不掉
![image](https://user-images.githubusercontent.com/82567447/118602536-68e27f00-b7e5-11eb-93d4-9278c2dab086.png)

**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Version (e.g. `kubectl get oc -n onecloud  -o yaml | grep -C 3 version`):

**Comment by yangyanqi0805** [comment]
![image](https://user-images.githubusercontent.com/82567447/118603409-73514880-b7e6-11eb-9445-8cd1615cb916.png)

**Comment by tb365** [comment]
接口调用错误。fix
