### ISSUE TITLE
新建腾讯云公网类型多可用区的lb实例报错

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/yunioncloud#11176]
**What happened**:
{
    "__reason__": "[TencentCloudSDKError] Code=InvalidParameter, Message=No available vip of disaster recovery in MasterZoneId ap-beijing-3, RequestId=6058488f-06cd-40bd-9721-d5b53be0fc5a",
    "__stage__": "OnLoadbalancerCreateComplete",
    "__status__": "ERROR"
}
**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by hoganlxj** [comment]
需要提到 release/3.5 分支

**Comment by tb365** [comment]
腾讯云资源紧张导致
