### ISSUE TITLE
云上azure硬盘快照的标签没有同步到云管平台

### ISSUE THREAD

**Issue by wenlong113** [yunionio/yunioncloud#11200]
**What happened**:
1. azure官网创建硬盘快照，且打上标签；
2. 云管平台同步azure云账号，该硬盘快照同步到云管平台，但是该硬盘快照的标签却没有同步下来
**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by ioito** [comment]
close #11191
