### ISSUE TITLE
权限projectmappings没有翻译

### ISSUE THREAD

**Issue by wenlong113** [yunionio/yunioncloud#11210]
**What happened**:
![image](https://user-images.githubusercontent.com/82567554/119470265-c133f680-bd7a-11eb-98a7-1d7b6727ecd4.png)

**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by GuoLiBin6** [comment]
已解决
https://git.yunion.io/projects/FE/repos/dashboard-ee/pull-requests/88/overview

**Comment by wenlong113** [comment]
经验证已解决
