### ISSUE TITLE
云管平台同步得到的阿里云证书没有名称。

### ISSUE THREAD

**Issue by wenlong113** [yunionio/yunioncloud#11225]
**What happened**:
![image](https://user-images.githubusercontent.com/82567554/119631674-b5ac0280-be42-11eb-900f-d32ce6ed2c21.png)

**Environment**:
office环境
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by tb365** [comment]
fix https://github.com/yunionio/yunioncloud/pull/11226
