### ISSUE TITLE
重启region不应该删除云管平台负载均衡证书的缓存

### ISSUE THREAD

**Issue by wenlong113** [yunionio/yunioncloud#11255]
**What happened**:
1. 在云管平台删除阿里云的ssl证书；
2. 同步阿里云云账号，把云上的证书再同步下来；
3. 重启region pod，阿里云的ssl证书的缓存被删除
**Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by tb365** [comment]
(fix）https://github.com/yunionio/yunioncloud/pull/11253
